spring:
  application:
    name: product-service
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.sql
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: local
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    streams:
      application-id: inventory-service
      properties:
        commit.interval.ms: 1000
        processing.guarantee: exactly_once_v2
        num.stream.threads: 12
        default.key.serde: org.apache.kafka.common.serialization.StringDeserializer
        default.value.serde: org.springframework.kafka.support.serializer.JsonDeserializer
        auto.register.schemas: true
        use.latest.version: true
        sasl.login.refresh.buffer.seconds: 300
        sasl.login.refresh.min.period.seconds: 60
        sasl.login.refresh.window.factor: 0.8
        sasl.login.refresh.window.jitter: 0.05
    listener:
      ack-mode: manual
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      sasl:
        login:
          refresh:
            buffer:
              seconds: 300
            min:
              period:
                seconds: 60
            window:
              jitter: 0.05
              factor: 0.8
  profiles:
    active: local
  main:
    banner-mode: console
logging:
  level:
    org.springframework: INFO
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
openapi:
  title: Product Service
  version: 1.0.0
  external-docs-url: https://github.com/miguel-gutierrez-smak-bewerbung/inventory-management-system