spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-service?currentSchema=local
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
topics:
  product:
    upsert: inventory.product.upsert.v1
    delete: inventory.product.delete.v1
    products-snapshot: inventory.product-snapshot.v1
    fail: inventory.product-snapshot.v1.fail
    retryFail: inventory.product-snapshot.v1.retry-fail